const DEFAULT_COLUMN_WIDTHS = {
  0: 300,
  1: 300,
  2: 220,
  3: 220,
  4: 145,
  5: 220,
  6: 145,
  7: 82,
  8: 60,
  9: 60,
  10: 150,
  11: 92,
  12: 150,
  13: 92,
  14: 220,
};

const DEFAULT_SHEET_ROWS = 5000;
const DEFAULT_ROW_PAGE_SIZE = 50;
const MAX_ROW_PAGE_SIZE = 500;
const ROW_LOCK_LAST_COLUMN_INDEX = 10;
const FIRST_CONFIRMATION_COLUMN_INDEX = 11;
const TAX_ITEM_NAME_COLUMN_INDEX = 0;
const TAX_MAIN_GROUP_COLUMN_INDEX = 2;
const TAX_SUB_GROUP_COLUMN_INDEX = 3;
const TAX_SUB_SUB_GROUP_COLUMN_INDEX = 4;
const TAX_SUPPORT_GROUP_COLUMN_INDEX = 5;
const TAX_DETAILED_GROUP_COLUMN_INDEX = 6;
const TAX_ITEM_CODE_COLUMN_INDEX = 12;
const CAIRO_TIMEZONE = "Africa/Cairo";
const FIRST_CONFIRMATION_EDIT_START_MINUTE = 8 * 60;
const FIRST_CONFIRMATION_EDIT_END_MINUTE = (15 * 60) + 30;
const ALLOWED_SHEET_TYPES = new Set(["custom", "item-master"]);

module.exports = {
  ALLOWED_SHEET_TYPES,
  CAIRO_TIMEZONE,
  DEFAULT_COLUMN_WIDTHS,
  DEFAULT_ROW_PAGE_SIZE,
  DEFAULT_SHEET_ROWS,
  FIRST_CONFIRMATION_COLUMN_INDEX,
  FIRST_CONFIRMATION_EDIT_END_MINUTE,
  FIRST_CONFIRMATION_EDIT_START_MINUTE,
  MAX_ROW_PAGE_SIZE,
  ROW_LOCK_LAST_COLUMN_INDEX,
  TAX_DETAILED_GROUP_COLUMN_INDEX,
  TAX_ITEM_CODE_COLUMN_INDEX,
  TAX_ITEM_NAME_COLUMN_INDEX,
  TAX_MAIN_GROUP_COLUMN_INDEX,
  TAX_SUB_GROUP_COLUMN_INDEX,
  TAX_SUB_SUB_GROUP_COLUMN_INDEX,
  TAX_SUPPORT_GROUP_COLUMN_INDEX,
};
